services:
  - name: twinnation
    url: https://twinnation.org/actuator/health
    interval: 15s
    failure-threshold: 3
    conditions:
      - "$STATUS == 200"
  - name: github
    url: https://api.github.com/healthz
    conditions:
      - "$STATUS == 200"