metrics: true
services:
  - name: twinnation
    url: "https://twinnation.org/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 1000"
  - name: cat-fact
    url: "https://cat-fact.herokuapp.com/facts/random"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].deleted == false"
      - "len([BODY].text) > 0"

kubernetes:
  cluster-mode: "out"
  auto-discover: true
  exclude-suffix:
    - primary
    - canary
  service-template:
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  namespaces:
    - name: databases
      service-suffix: "databases.svc.cluster.local"
      health-api: "/health"
    - name: services
      service-suffix: "services.svc.cluster.local"
      health-api: "/health"