services:
  - name: twinnation
    url: https://twinnation.org/actuator/health
    interval: 15
    failure-threshold: 3
    conditions:
      - "$STATUS == 200"
  - name: github
    url: https://github.com
    conditions:
      - "$STATUS != 400"
      - "$STATUS != 500"