metrics: true
services:
  - name: Twinnation
    url: https://twinnation.org/health
    interval: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 20"
  - name: GitHub API
    url: https://api.github.com/healthz
    interval: 30s
    conditions:
      - "[STATUS] == 200"