metrics: true
services:
  - name: Twinnation
    url: https://twinnation.org/actuator/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: GitHub API
    url: https://api.github.com/healthz
    interval: 30s
    conditions:
      - "[STATUS] == 200"