metrics: true
services:
  - name: twinnation
    url: "https://twinnation.org/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 1000"
  - name: cat-fact
    url: "https://cat-fact.herokuapp.com/facts/random"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].deleted == false"
      - "len([BODY].text) > 0"