metrics: true
services:
  - name: Twinnation
    url: https://twinnation.org/health
    interval: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
      - "[BODY].status == UP"
  - name: Example
    url: https://example.org/
    interval: 30s
    conditions:
      - "[STATUS] == 200"