version: "3.8"
services:
    gatus:
        image: twinproduction/gatus:latest
        ports:
          - 8080:8080
        volumes:
          - ./config.yaml:/config/config.yaml

    mattermost-preview:
        image: mattermost/mattermost-preview:latest
        ports:
          - 8065:8065